project:
  type: website
  output-dir: docs

website:
  title: "NRG's Project Lab"
  navbar:
    search: true
    left:
    
      - text: About Us
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://github.com/orgs/emu-hacettepe-analytics/teams/nrg

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2024 - N R G" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: minty
    
    css: styles.css
    code-fold: true


editor: visual

